graph LR;
  s[Splash];
  mm[Main Menu];
  ng(Character Selection);
  lg(Save Game Selection);
  opt[Options Menu];
  q((Close Game));

  s--Game / Asset Loading--> mm;
  mm--New Game-->ng;
  ng--Back-->mm;
  mm--Load Game-->lg;
  lg--Back-->mm;
  mm--Options-->opt;
  opt--Back-->mm;
  mm--Quit Game-->q;
