graph LR
    s[Splash];
    mm[Main Menu];
    ng(Character Selection);
    lg(Save Game Selection);
    opt[Options Menu];
    q[[Close Game]];
    s--Game / Asset Loading--> mm;
    mm--New Game-->ng;
    mm--Load Game-->lg;
    mm--Options-->opt;
    mm--Quit Game-->q;